using Microsoft.Maui.Controls;

namespace HelloMaui;

public partial class MainPage : ContentPage
{
    public MainPage()
    {
        InitializeComponent(); // This inflates XAML generated by the MauiXaml source generator
    }
}
