name: Build Android (GitHub Actions)

on:
  push:
    branches: [ main ]
  release:
    types: [ created ]
  workflow_dispatch:

jobs:
  build-android:
    runs-on: macos-14
    timeout-minutes: 120

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET SDK 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Setup Java 17 (Temurin)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Android SDK (cmdline-tools latest)
        uses: android-actions/setup-android@v3
        with:
          packages: "platform-tools platforms;android-34 build-tools;34.0.0"

      - name: Accept Android SDK licenses
        run: yes | sdkmanager --licenses

      - name: Install MAUI Android workload
        run: dotnet workload install maui-android

      - name: Show dotnet info
        run: dotnet --info

      - name: Restore dependencies
        run: dotnet restore

      - name: Build and publish APK
        env:
          KEYSTORE_PATH: ${{ runner.temp }}/release.keystore
        run: |
          PUBLISH_DIR=./publish
          mkdir -p "$PUBLISH_DIR"

          if [ -n "${{ secrets.KEYSTORE_BASE64 }}" ]; then
            echo "Keystore secrets detected — producing a signed release APK"
            echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > "$KEYSTORE_PATH"

            dotnet publish ./HelloMaui.csproj -f net8.0-android -c Release -o "$PUBLISH_DIR" \
              -p:AndroidKeyStore=true \
              -p:AndroidSigningKeyStore="$KEYSTORE_PATH" \
              -p:AndroidSigningStorePass="${{ secrets.KEYSTORE_PASSWORD }}" \
              -p:AndroidSigningKeyAlias="${{ secrets.KEY_ALIAS }}" \
              -p:AndroidSigningKeyPass="${{ secrets.KEY_PASSWORD }}"
          else
            echo "No keystore provided — producing an unsigned release APK"
            dotnet publish ./HelloMaui.csproj -f net8.0-android -c Release -o "$PUBLISH_DIR"

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: publish/**/*.apk

      - name: List publish artifacts
        run: |
          echo "APK(s) found:"
          find publish -type f -name "*.apk" -print